packages:
  - '.'
  - 'youtube-mp3-extension'

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'

onlyBuiltDependencies:
  - esbuild
  - ffmpeg-static
  - sharp
  - unrs-resolver
  - youtube-dl-exec
